baseURL = "http://gtraskas.github.io/"
languageCode = "en-us"
title = "A data science blog"
theme = "minimal"
disqusShortname = "gtraskas" # delete this to disable disqus comments
# googleAnalytics = ""

[params]
    author = "George Traskas"
    description = "Hi, I am George Traskas. In my free time I take an interest in working on statistics, machine learning, and data."
    githubUsername = "gtraskas"
    accent = "#336699"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "github"
    highlightLanguages = ["python", "R", "Markdown"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

[[menu.main]]
    url = "/about/me"
    name = "About"
    weight = 2

[[menu.main]]
    url = "/project/"
    name = "Projects"
    weight = 3

[[menu.main]]
    url = "/post/"
    name = "Posts"
    weight = 4

# Social icons to be shown on the right-hand side of the navigation bar
# The "name" field should match the name of the icon to be used
# The list of available icons can be found at http://fontawesome.io/icons/

[[menu.icon]]
    url = "mailto:georgiost77@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/gtraskas/"
    name = "github"
    weight = 2

#[[menu.icon]]
#    url = "https://twitter.com/username/"
#    name = "twitter"
#    weight = 3

[[menu.icon]]
    url = "http://gr.linkedin.com/in/georgiostraskas"
    name = "linkedin"
    weight = 4

#[[menu.icon]]
#    url = "https://www.stackoverflow.com/username/"
#    name = "stack-overflow"
#    weight = 5
